### ISSUE TITLE
Where are the codes?

### ISSUE THREAD

**Issue by vhphan** [PacktPublishing/Mastering-PostgreSQL-15-#1]
Can't find any codes in this repo.

**Comment by Packt-Kavyashreek** [comment]
All the code was tested in SQL shell from the word files itself. Hence it has no code files on repo.

**Comment by Narsskrarc** [comment]
Very weird indeed.
In the book you write `You can download the example code files for this book from GitHub at ...`.
Shouldn't you keep what you promise?
